[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.package]
version = "0.1.0"
edition = "2021"
rust-version = "1.85"
license = "AGPL-3.0-or-later"
repository = "https://github.com/Sarcastic-Soul/Foolscap"
authors = ["Anish Kumar <anishisbusy@gmail.com>"]

[workspace.dependencies]
pdf-core = { path = "crates/pdf-core" }

lopdf = "0.34"
mupdf = { version = "0.8", default-features = false, features = ["base14-fonts"] }
image = { version = "0.25", default-features = false }
flate2 = "1"
thiserror = "2"
tracing = "0.1"

anyhow = "1"
clap = { version = "4", features = ["derive"] }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[profile.release]
lto = "thin"
codegen-units = 1
strip = true
